### ISSUE TITLE
Want to do some work and refining on this

### ISSUE THREAD

**Issue by CthulhuCrisis** [FredYeye/Demon-s-Crest-Rando#1]
Hey! I'm a big randomizer player, mostly Jets of Time (Chrono Trigger Randomizer). I wanted to try to make some changes to this rando, attempt to start a small community of competitive players, and refine this down to what makes this game great.

Is that okay? I wouldn't want to do anything without permission.

**Comment by FredYeye** [comment]
(I realize this comment is over a year old by now, I believe/hope I replied to this on the Gargoyle's Quest Community discord.)

Any fixes or suggestions are welcome! Though right now the biggest problem is corrupted graphics, which I'm not sure how to fix in a good way.
